language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
script:
  - bundle exec rspec spec --order rand --color
  # - bundle exec cucumber --tags ~@linking --no-profile --color --format progress --strict
notifications:
  email: false
matrix:
  allow_failures:
    - rvm: 2.0.0
